name: first-github-action
on: 
  push:
    branches:
      -main
      -devel
      -develop
jobs:
  write-to-console:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello world from master'
